name: Generate Snake

on:
  push:
    branches:
      - main  # nebo jinÃ¡ vÄ›tev, pokud pouÅ¾Ã­vÃ¡Å¡ nÄ›co jinÃ©ho
  schedule:
    - cron: "0 0 * * *"  # kaÅ¾dÃ½ den v 00:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # <--- DÅ®LEÅ½ITÃ‰! potÅ™ebnÃ© pro plnÃ½ git history a sprÃ¡vnÃ½ push

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: AdamKostelenec
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          commit_message: "ğŸ Generate contribution graph snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
